# CSS选择器配置文件
# 注意：小红书等网站经常变更DOM结构，需要定期更新

xiaohongshu:
  search:
    note_cards: ".note-item, .search-item, [class*='note']"
    note_link: "a"
    note_title: ".title, [class*='title']"
    note_author: ".author, [class*='author']"

  detail:
    title: "h1, .title, [class*='title']"
    content: ".content, [class*='content'], [class*='desc']"
    likes: "[class*='like'], .like-count"
    collects: "[class*='collect'], .collect-count"
    comments: "[class*='comment'], .comment-count"
    images: "img[src*='http']"

baidu:
  search:
    result_container: ".result, .c-container"
    result_link: "h3 a, .t a"
    result_title: "h3 a, .t a"

ctrip:
  hotel:
    search_input: "#searchBoxInput"
    hotel_list: ".hotel_item"
    hotel_name: ".hotel_name"
    hotel_price: ".J_price_lowList"
    hotel_rating: ".score"

  flight:
    search_button: ".search-btn"
    flight_list: ".flight-item"
    flight_number: ".flight-no"
    airline: ".airline-name"
    price: ".price"
